language: ruby
addons:
  chrome: stable
  apt:
    packages:
      - ca-certificates
cache: bundler
dist: xenial
before_install:
  - gem update --system
  - gem --version
script: xvfb-run bundle exec rake
